name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  url:
    description: 'url of the api you are willing to test'
    required: true
  username:
    description: 'username used for the tests (must be unique)'
    required: false
  email:
    description: 'email used for the tests (must be unique)'
    required: false
  password:
    description: 'password used for the tests'
    required: false
  start:
    description: 'command to run the project'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
